name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches-ignore: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  ci:
    uses: Nicola-Ibrahim/Tracing-Objectives-Backwards-Devops/.github/workflows/reusable-ci-python.yml@main
    with:
      python-version: '3.12'
      environment: production